### ISSUE TITLE
:devel is missing `make` and `bundletester`

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/charmbox#37]
These are definitely required for charmbox to be used as part of the review / CI process.

**Comment by lazypower** [comment]
I'm not saying its not missing (i just verified) but uhh

https://github.com/juju-solutions/charmbox/blob/devel/install-review-tools.sh#L31

Wat

**Comment by johnsca** [comment]
It's getting removed after: https://github.com/juju-solutions/charmbox/blob/devel/Dockerfile#L6

**Comment by pengale** [comment]
Also needs "gcc" to compile bundletester, if we're installing it via pip.

It might be a good idea to just apt install build-essential.

**Comment by lazypower** [comment]
we can install all that prior to installing bundletester and clean it up. build-essential pulls in quite a large suite of dependencies and i'm still trying to keep the image smaller than it has been in the past.

**Comment by lazypower** [comment]
And as commented elsewhere, 40mb isn't that huge of an impact considering. I'm +1 to build-essential in the default image now.

**Comment by lazypower** [comment]
This should all be addressed by #45 

Which folds in all the necessary sub-componentry we expect to be found in our test env.

**Comment by kwmonroe** [comment]
This isn't fixed yet.. Looks like charmbox:devel has failed to build since Aug 17.  Sample failed build:

https://hub.docker.com/r/jujusolutions/charmbox/builds/bbzs6eo9vgygymlcwby5qjp/

It's missing `libssl-dev`:

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:429:30: fatal error: openssl/opensslv.h: No such file or directory
```

^^ That failure comes when trying to pip install `cryptography-1.4`, which looks to be a dep from  `bundletester`.

**Comment by lazypower** [comment]
@kwmonroe can you propose a patch to add in the libssl-dev package?

Propose it against master, and i'll rebase it into devel.

**Comment by kwmonroe** [comment]
@chuckbutler i tried to build locally to repro the failure on :master and :devel, but the damn thing succeeded.  i'm not confident that `libssl-dev` is the only missing package, but i can't verify that unless i can build like docker hub does.  Any tips on replicating the failing env seen here:

https://hub.docker.com/r/jujusolutions/charmbox/builds/

Fwiw, my local builds don't have a reference to `cryptography-1.4` (or any other version) at all, so i really don't think i'm building the same as docker hub.. I'm just running `docker build -t charmbox .` from a pwd with the most recent git clone of this repo.

**Comment by lazypower** [comment]
Thats effectively what the hub is doing. I'll give it a look today and see if we can suss out whats happening.

**Comment by lazypower** [comment]
Fixed with #56 and #55
